### ISSUE TITLE
Replacing "Buy with Seeds" Text with "Squad Discount"

### ISSUE THREAD

**Issue by luxumbra** [luxumbra/mf-irl-astro#11]
We are shifting our purchase options and as a part of this, we need to replace the text "Buy with Seeds" with "Squad Discount".

How is this going to work? Will the user be choosing how many tickets they want and getting the discount price applied before they leave the MF website or will it just link through to Stripe?

**Comment by peth-yursick** [comment]
I was thinking just duplicating the "Dump Seeds" tally form, tripling the prices & adding a note explaining that this buys 3 tickets in one go & you get 4th one for free

**Comment by peth-yursick** [comment]
So here's the "Squad Discount" form https://tally.so/forms/mVj4La/share

**Comment by peth-yursick** [comment]
Bringing frens? Get the 4th ticket for free!

4 Standard tickets ~~€800~~ €600
4 Patron tickets✨~~€1680~~ €1200

**Comment by luxumbra** [comment]
Cool, OK. That keeps it simple in terms of development. 👍🏻

**Comment by luxumbra** [comment]
Has been live for a couple weeks so closing this
